apiVersion: v1
kind: Service
metadata:
  name: git-steer-ui
  namespace: fabric
  labels:
    app: git-steer-ui
spec:
  selector:
    app: git-steer-ui
  ports:
    - port: 80
      targetPort: http
      name: http
